
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class WorkerWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label11;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Table personDataTable;
		private global::Gtk.Entry emailEntry;
		private global::Gtk.Entry fnameEntry;
		private global::Gtk.Entry hnrEntry;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.Label label21;
		private global::Gtk.Entry lnameEntry;
		private global::Gtk.Entry mobileEntry;
		private global::Gtk.Entry plzEntry;
		private global::Gtk.Entry streetEntry;
		private global::Gtk.Entry telEntry;
		private global::Gtk.Entry villageEntry;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label12;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Table timeTable;
		private global::Gtk.ComboBox areaCombobox;
		private global::Gtk.Label label22;
		private global::Gtk.Label label23;
		private global::Gtk.Label label24;
		private global::Gtk.Label label25;
		private global::Gtk.ComboBox taskCombobox;
		private global::Gtk.ComboBox timeCombobox;
		private global::Gtk.ComboBox typCombobox;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button saveButton;
		private global::Gtk.Button button18;
		private global::Gtk.Button backButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.WorkerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.WorkerWidget";
			// Container child WidgetLibrary.WorkerWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Personendaten");
			this.vbox3.Add (this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.HeightRequest = 6;
			this.hseparator3.Name = "hseparator3";
			this.vbox3.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator3]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.personDataTable = new global::Gtk.Table (((uint)(9)), ((uint)(2)), false);
			this.personDataTable.Name = "personDataTable";
			this.personDataTable.RowSpacing = ((uint)(6));
			this.personDataTable.ColumnSpacing = ((uint)(6));
			// Container child personDataTable.Gtk.Table+TableChild
			this.emailEntry = new global::Gtk.Entry ();
			this.emailEntry.CanFocus = true;
			this.emailEntry.Name = "emailEntry";
			this.emailEntry.IsEditable = true;
			this.emailEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.emailEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.emailEntry]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.fnameEntry = new global::Gtk.Entry ();
			this.fnameEntry.CanFocus = true;
			this.fnameEntry.Name = "fnameEntry";
			this.fnameEntry.IsEditable = true;
			this.fnameEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.fnameEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.fnameEntry]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.hnrEntry = new global::Gtk.Entry ();
			this.hnrEntry.CanFocus = true;
			this.hnrEntry.Name = "hnrEntry";
			this.hnrEntry.IsEditable = true;
			this.hnrEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.hnrEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.hnrEntry]));
			w5.TopAttach = ((uint)(8));
			w5.BottomAttach = ((uint)(9));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Vorname :");
			this.personDataTable.Add (this.label13);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label13]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Nachname :");
			this.personDataTable.Add (this.label14);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label14]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Email :");
			this.personDataTable.Add (this.label15);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label15]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Mobil :");
			this.personDataTable.Add (this.label16);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label16]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Telefon :");
			this.personDataTable.Add (this.label17);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label17]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("PLZ :");
			this.personDataTable.Add (this.label18);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label18]));
			w11.TopAttach = ((uint)(5));
			w11.BottomAttach = ((uint)(6));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Ort :");
			this.personDataTable.Add (this.label19);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label19]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 1F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Straße :");
			this.personDataTable.Add (this.label20);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label20]));
			w13.TopAttach = ((uint)(7));
			w13.BottomAttach = ((uint)(8));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 1F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Hnr. :");
			this.personDataTable.Add (this.label21);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.label21]));
			w14.TopAttach = ((uint)(8));
			w14.BottomAttach = ((uint)(9));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.lnameEntry = new global::Gtk.Entry ();
			this.lnameEntry.CanFocus = true;
			this.lnameEntry.Name = "lnameEntry";
			this.lnameEntry.IsEditable = true;
			this.lnameEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.lnameEntry);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.lnameEntry]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.mobileEntry = new global::Gtk.Entry ();
			this.mobileEntry.CanFocus = true;
			this.mobileEntry.Name = "mobileEntry";
			this.mobileEntry.IsEditable = true;
			this.mobileEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.mobileEntry);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.mobileEntry]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.plzEntry = new global::Gtk.Entry ();
			this.plzEntry.CanFocus = true;
			this.plzEntry.Name = "plzEntry";
			this.plzEntry.IsEditable = true;
			this.plzEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.plzEntry);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.plzEntry]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.streetEntry = new global::Gtk.Entry ();
			this.streetEntry.CanFocus = true;
			this.streetEntry.Name = "streetEntry";
			this.streetEntry.IsEditable = true;
			this.streetEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.streetEntry);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.streetEntry]));
			w18.TopAttach = ((uint)(7));
			w18.BottomAttach = ((uint)(8));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.telEntry = new global::Gtk.Entry ();
			this.telEntry.CanFocus = true;
			this.telEntry.Name = "telEntry";
			this.telEntry.IsEditable = true;
			this.telEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.telEntry);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.telEntry]));
			w19.TopAttach = ((uint)(4));
			w19.BottomAttach = ((uint)(5));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child personDataTable.Gtk.Table+TableChild
			this.villageEntry = new global::Gtk.Entry ();
			this.villageEntry.CanFocus = true;
			this.villageEntry.Name = "villageEntry";
			this.villageEntry.IsEditable = true;
			this.villageEntry.InvisibleChar = '●';
			this.personDataTable.Add (this.villageEntry);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.personDataTable [this.villageEntry]));
			w20.TopAttach = ((uint)(6));
			w20.BottomAttach = ((uint)(7));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.personDataTable);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.personDataTable]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w22.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.WidthRequest = 6;
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Einteilung");
			this.vbox2.Add (this.label12);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label12]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.HeightRequest = 6;
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.timeTable = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.timeTable.Name = "timeTable";
			this.timeTable.RowSpacing = ((uint)(6));
			this.timeTable.ColumnSpacing = ((uint)(6));
			// Container child timeTable.Gtk.Table+TableChild
			this.areaCombobox = global::Gtk.ComboBox.NewText ();
			this.areaCombobox.Name = "areaCombobox";
			this.timeTable.Add (this.areaCombobox);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.timeTable [this.areaCombobox]));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Arbeitsplatz :");
			this.timeTable.Add (this.label22);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.timeTable [this.label22]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 1F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Aufgabe :");
			this.timeTable.Add (this.label23);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.timeTable [this.label23]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xalign = 1F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Typ :");
			this.timeTable.Add (this.label24);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.timeTable [this.label24]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.Xalign = 1F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Schicht :");
			this.timeTable.Add (this.label25);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.timeTable [this.label25]));
			w30.TopAttach = ((uint)(3));
			w30.BottomAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.taskCombobox = global::Gtk.ComboBox.NewText ();
			this.taskCombobox.Name = "taskCombobox";
			this.timeTable.Add (this.taskCombobox);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.timeTable [this.taskCombobox]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.timeCombobox = global::Gtk.ComboBox.NewText ();
			this.timeCombobox.Name = "timeCombobox";
			this.timeTable.Add (this.timeCombobox);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.timeTable [this.timeCombobox]));
			w32.TopAttach = ((uint)(3));
			w32.BottomAttach = ((uint)(4));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child timeTable.Gtk.Table+TableChild
			this.typCombobox = global::Gtk.ComboBox.NewText ();
			this.typCombobox.Name = "typCombobox";
			this.timeTable.Add (this.typCombobox);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.timeTable [this.typCombobox]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.timeTable);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.timeTable]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w35.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.HeightRequest = 6;
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Homogeneous = true;
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseUnderline = true;
			// Container child saveButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Speichern");
			w42.UseUnderline = true;
			w39.Add (w42);
			w38.Add (w39);
			this.saveButton.Add (w38);
			this.hbuttonbox1.Add (this.saveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.saveButton]));
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			this.button18.UseUnderline = true;
			// Container child button18.Gtk.Container+ContainerChild
			global::Gtk.Alignment w47 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w48 = new global::Gtk.HBox ();
			w48.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w49 = new global::Gtk.Image ();
			w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w48.Add (w49);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w51 = new global::Gtk.Label ();
			w51.LabelProp = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
			w51.UseUnderline = true;
			w48.Add (w51);
			w47.Add (w48);
			this.button18.Add (w47);
			this.hbuttonbox1.Add (this.button18);
			global::Gtk.ButtonBox.ButtonBoxChild w55 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button18]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.backButton = new global::Gtk.Button ();
			this.backButton.CanFocus = true;
			this.backButton.Name = "button19";
			this.backButton.UseUnderline = true;
			// Container child button19.Gtk.Container+ContainerChild
			global::Gtk.Alignment w56 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w57 = new global::Gtk.HBox ();
			w57.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w57.Add (w58);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w60 = new global::Gtk.Label ();
			w60.LabelProp = global::Mono.Unix.Catalog.GetString ("Zurück");
			w60.UseUnderline = true;
			w57.Add (w60);
			w56.Add (w57);
			this.backButton.Add (w56);
			this.hbuttonbox1.Add (this.backButton);
			global::Gtk.ButtonBox.ButtonBoxChild w64 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.backButton]));
			w64.Position = 2;
			w64.Expand = false;
			w64.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w65.Position = 2;
			w65.Expand = false;
			w65.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
			this.button18.Clicked += new global::System.EventHandler (this.OnButton18Clicked);
			this.backButton.Clicked += new global::System.EventHandler (this.OnButton19Clicked);
		}
	}
}
