
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class TimesWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label headerLabel;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView timesTreeview;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label timesManagementHeaderLabel;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button newButton;
		private global::Gtk.Button refreshButton;
		private global::Gtk.Button deleteButton;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label outputHeaderLabel;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button printButton;
		private global::Gtk.Button printViewButton;
		private global::Gtk.Button exportButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.TimesWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.TimesWidget";
			// Container child WidgetLibrary.TimesWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.headerLabel = new global::Gtk.Label ();
			this.headerLabel.Name = "headerLabel";
			this.headerLabel.Xalign = 0F;
			this.headerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Schichten");
			this.vbox1.Add (this.headerLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.headerLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.timesTreeview = new global::Gtk.TreeView ();
			this.timesTreeview.CanFocus = true;
			this.timesTreeview.Name = "timesTreeview";
			this.GtkScrolledWindow.Add (this.timesTreeview);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.timesManagementHeaderLabel = new global::Gtk.Label ();
			this.timesManagementHeaderLabel.Name = "timesManagementHeaderLabel";
			this.timesManagementHeaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Verwaltung");
			this.vbox2.Add (this.timesManagementHeaderLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.timesManagementHeaderLabel]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.HeightRequest = 6;
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.newButton = new global::Gtk.Button ();
			this.newButton.CanFocus = true;
			this.newButton.Name = "newButton";
			this.newButton.UseUnderline = true;
			// Container child newButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Neu");
			w10.UseUnderline = true;
			w7.Add (w10);
			w6.Add (w7);
			this.newButton.Add (w6);
			this.hbuttonbox2.Add (this.newButton);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.newButton]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.refreshButton = new global::Gtk.Button ();
			this.refreshButton.CanFocus = true;
			this.refreshButton.Name = "refreshButton";
			this.refreshButton.UseUnderline = true;
			// Container child refreshButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_refresh", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("aktualisieren");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.refreshButton.Add (w15);
			this.hbuttonbox2.Add (this.refreshButton);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.refreshButton]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.deleteButton = new global::Gtk.Button ();
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseUnderline = true;
			// Container child deleteButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("löschen");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.deleteButton.Add (w24);
			this.hbuttonbox2.Add (this.deleteButton);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.deleteButton]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w34.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.WidthRequest = 6;
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.outputHeaderLabel = new global::Gtk.Label ();
			this.outputHeaderLabel.Name = "outputHeaderLabel";
			this.outputHeaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Ausgabe");
			this.vbox3.Add (this.outputHeaderLabel);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.outputHeaderLabel]));
			w36.Position = 0;
			w36.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.HeightRequest = 6;
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.printButton = new global::Gtk.Button ();
			this.printButton.CanFocus = true;
			this.printButton.Name = "printButton";
			this.printButton.UseUnderline = true;
			// Container child printButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Drucken");
			w42.UseUnderline = true;
			w39.Add (w42);
			w38.Add (w39);
			this.printButton.Add (w38);
			this.hbuttonbox1.Add (this.printButton);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.printButton]));
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.printViewButton = new global::Gtk.Button ();
			this.printViewButton.CanFocus = true;
			this.printViewButton.Name = "printViewButton";
			this.printViewButton.UseUnderline = true;
			// Container child printViewButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w47 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w48 = new global::Gtk.HBox ();
			w48.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w49 = new global::Gtk.Image ();
			w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print-preview", global::Gtk.IconSize.Menu);
			w48.Add (w49);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w51 = new global::Gtk.Label ();
			w51.LabelProp = global::Mono.Unix.Catalog.GetString ("Druckvorschau");
			w51.UseUnderline = true;
			w48.Add (w51);
			w47.Add (w48);
			this.printViewButton.Add (w47);
			this.hbuttonbox1.Add (this.printViewButton);
			global::Gtk.ButtonBox.ButtonBoxChild w55 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.printViewButton]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.exportButton = new global::Gtk.Button ();
			this.exportButton.CanFocus = true;
			this.exportButton.Name = "exportButton";
			this.exportButton.UseUnderline = true;
			// Container child exportButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w56 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w57 = new global::Gtk.HBox ();
			w57.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			w57.Add (w58);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w60 = new global::Gtk.Label ();
			w60.LabelProp = global::Mono.Unix.Catalog.GetString ("PDF - Export");
			w60.UseUnderline = true;
			w57.Add (w60);
			w56.Add (w57);
			this.exportButton.Add (w56);
			this.hbuttonbox1.Add (this.exportButton);
			global::Gtk.ButtonBox.ButtonBoxChild w64 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.exportButton]));
			w64.Position = 2;
			w64.Expand = false;
			w64.Fill = false;
			this.vbox3.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox1]));
			w65.Position = 2;
			w65.Expand = false;
			w65.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w66.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w67.Position = 2;
			w67.Expand = false;
			w67.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.timesTreeview.CursorChanged += new global::System.EventHandler (this.OnTimesTreeviewCursorChanged);
			this.newButton.Clicked += new global::System.EventHandler (this.OnNewButtonClicked);
			this.deleteButton.Clicked += new global::System.EventHandler (this.OnDeleteButtonClicked);
			this.printButton.Clicked += new global::System.EventHandler (this.OnPrintButtonClicked);
			this.printViewButton.Clicked += new global::System.EventHandler (this.OnPrintViewButtonClicked);
			this.exportButton.Clicked += new global::System.EventHandler (this.OnExportButtonClicked);
		}
	}
}
