
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary {
	public partial class SelectWidget {
		private global::Gtk.HButtonBox hbuttonbox3;
		
		private global::Gtk.Button planButton;
		
		private global::Gtk.VBox vbox6;

		
		private global::Gtk.Label label9;
		
		private global::Gtk.Button personButton;
		
		private global::Gtk.VBox vbox5;

		
		private global::Gtk.Label personsButtonLabel;
		
		private global::Gtk.Button timesButton;
		
		private global::Gtk.VBox vbox3;

		private global::Gtk.Label timesButtonLabel;
		
		protected virtual void Build() {
			global::Stetic.Gui.Initialize(this);
			// Widget WidgetLibrary.SelectWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "WidgetLibrary.SelectWidget";
			// Container child WidgetLibrary.SelectWidget.Gtk.Container+ContainerChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.Homogeneous = true;
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.planButton = new global::Gtk.Button();
			this.planButton.WidthRequest = 200;
			this.planButton.HeightRequest = 200;
			this.planButton.CanFocus = true;
			this.planButton.Name = "planButton";
			// Container child planButton.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Pläne");
			this.vbox6.Add(this.label9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label9]));
			w2.Position = 1;
			w2.Fill = false;
			this.planButton.Add(this.vbox6);
			this.planButton.Label = null;
			this.hbuttonbox3.Add(this.planButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.planButton]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.personButton = new global::Gtk.Button();
			this.personButton.CanFocus = true;
			this.personButton.Name = "personButton";
			// Container child personButton.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.personsButtonLabel = new global::Gtk.Label();
			this.personsButtonLabel.Name = "personsButtonLabel";
			this.personsButtonLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Personen");
			this.vbox5.Add(this.personsButtonLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.personsButtonLabel]));
			w6.Position = 1;
			w6.Fill = false;
			this.personButton.Add(this.vbox5);
			this.personButton.Label = null;
			this.hbuttonbox3.Add(this.personButton);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.personButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.timesButton = new global::Gtk.Button();
			this.timesButton.WidthRequest = 200;
			this.timesButton.HeightRequest = 200;
			this.timesButton.CanFocus = true;
			this.timesButton.Name = "timesButton";
			// Container child timesButton.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;

			// Container child vbox3.Gtk.Box+BoxChild
			this.timesButtonLabel = new global::Gtk.Label();
			this.timesButtonLabel.Name = "timesButtonLabel";
			this.timesButtonLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Schichten");
			this.vbox3.Add(this.timesButtonLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.timesButtonLabel]));
			w10.Position = 1;
			w10.Fill = false;
			this.timesButton.Add(this.vbox3);
			this.timesButton.Label = null;
			this.hbuttonbox3.Add(this.timesButton);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.timesButton]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.hbuttonbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.Hide();
			this.planButton.Clicked += new global::System.EventHandler(this.onplanButtonClicked);
			this.personButton.Clicked += new global::System.EventHandler(this.onpersonButtonClicked);
			this.timesButton.Clicked += new global::System.EventHandler(this.OnTimesButtonClicked);
		}
	}
}
