
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class PersonWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Table table1;
		private global::Gtk.ComboBox areaCombobox;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Entry fnameEntry;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.Entry lnameEntry;
		private global::Gtk.ComboBox taskCombobox;
		private global::Gtk.ComboBox timesCombobox;
		private global::Gtk.ComboBox typCombobox;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView personalTreeView;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label PVHeaderLabel;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button PersonAddButton;
		private global::Gtk.Button PersonEditButton;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label PHeaderLabel;
		private global::Gtk.HButtonBox managementHbuttonbox;
		private global::Gtk.Button printButton;
		private global::Gtk.Button printViewButton;
		private global::Gtk.Button exportButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.PersonWidget
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 750;
			this.HeightRequest = 650;
			this.Name = "WidgetLibrary.PersonWidget";
			// Container child WidgetLibrary.PersonWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 10;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.areaCombobox = global::Gtk.ComboBox.NewText ();
			this.areaCombobox.AppendText ("");
			this.areaCombobox.AppendText ("");
			this.areaCombobox.Name = "areaCombobox";
			this.table1.Add (this.areaCombobox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.areaCombobox]));
			w2.LeftAttach = ((uint)(4));
			w2.RightAttach = ((uint)(5));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table1.Add (this.fixed2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed2]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fnameEntry = new global::Gtk.Entry ();
			this.fnameEntry.CanFocus = true;
			this.fnameEntry.Name = "fnameEntry";
			this.fnameEntry.IsEditable = true;
			this.fnameEntry.InvisibleChar = '●';
			this.table1.Add (this.fnameEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.fnameEntry]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Vorname :");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Nachname :");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Abteil :");
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Aufgabe :");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Schicht :");
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Typ :");
			this.table1.Add (this.label9);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lnameEntry = new global::Gtk.Entry ();
			this.lnameEntry.CanFocus = true;
			this.lnameEntry.Name = "lnameEntry";
			this.lnameEntry.IsEditable = true;
			this.lnameEntry.InvisibleChar = '●';
			this.table1.Add (this.lnameEntry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.lnameEntry]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.taskCombobox = global::Gtk.ComboBox.NewText ();
			this.taskCombobox.Name = "taskCombobox";
			this.table1.Add (this.taskCombobox);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.taskCombobox]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(4));
			w12.RightAttach = ((uint)(5));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.timesCombobox = global::Gtk.ComboBox.NewText ();
			this.timesCombobox.Name = "timesCombobox";
			this.table1.Add (this.timesCombobox);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.timesCombobox]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(4));
			w13.RightAttach = ((uint)(5));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.typCombobox = global::Gtk.ComboBox.NewText ();
			this.typCombobox.Name = "typCombobox";
			this.table1.Add (this.typCombobox);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.typCombobox]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.personalTreeView = new global::Gtk.TreeView ();
			this.personalTreeView.CanFocus = true;
			this.personalTreeView.Name = "personalTreeView";
			this.GtkScrolledWindow.Add (this.personalTreeView);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w17.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.HeightRequest = 6;
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.PVHeaderLabel = new global::Gtk.Label ();
			this.PVHeaderLabel.Name = "PVHeaderLabel";
			this.PVHeaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Personenverwaltung");
			this.vbox3.Add (this.PVHeaderLabel);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.PVHeaderLabel]));
			w19.Position = 0;
			w19.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Homogeneous = true;
			this.hbuttonbox1.Spacing = 3;
			this.hbuttonbox1.BorderWidth = ((uint)(3));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.PersonAddButton = new global::Gtk.Button ();
			this.PersonAddButton.CanFocus = true;
			this.PersonAddButton.Name = "PersonAddButton";
			this.PersonAddButton.UseUnderline = true;
			// Container child PersonAddButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("Neu");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.PersonAddButton.Add (w20);
			this.hbuttonbox1.Add (this.PersonAddButton);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.PersonAddButton]));
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.PersonEditButton = new global::Gtk.Button ();
			this.PersonEditButton.CanFocus = true;
			this.PersonEditButton.Name = "PersonEditButton";
			this.PersonEditButton.UseUnderline = true;
			// Container child PersonEditButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.PersonEditButton.Add (w29);
			this.hbuttonbox1.Add (this.PersonEditButton);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.PersonEditButton]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox3.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox1]));
			w38.Position = 1;
			w38.Expand = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w39.Position = 0;
			w39.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.WidthRequest = 6;
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.PHeaderLabel = new global::Gtk.Label ();
			this.PHeaderLabel.Name = "PHeaderLabel";
			this.PHeaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Verwaltung");
			this.vbox4.Add (this.PHeaderLabel);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.PHeaderLabel]));
			w41.Position = 0;
			w41.Expand = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.managementHbuttonbox = new global::Gtk.HButtonBox ();
			this.managementHbuttonbox.Name = "managementHbuttonbox";
			this.managementHbuttonbox.Homogeneous = true;
			this.managementHbuttonbox.Spacing = 3;
			this.managementHbuttonbox.BorderWidth = ((uint)(3));
			// Container child managementHbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.printButton = new global::Gtk.Button ();
			this.printButton.CanFocus = true;
			this.printButton.Name = "printButton";
			this.printButton.UseUnderline = true;
			// Container child printButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Drucken");
			w46.UseUnderline = true;
			w43.Add (w46);
			w42.Add (w43);
			this.printButton.Add (w42);
			this.managementHbuttonbox.Add (this.printButton);
			global::Gtk.ButtonBox.ButtonBoxChild w50 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.managementHbuttonbox [this.printButton]));
			w50.Expand = false;
			w50.Fill = false;
			// Container child managementHbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.printViewButton = new global::Gtk.Button ();
			this.printViewButton.CanFocus = true;
			this.printViewButton.Name = "printViewButton";
			this.printViewButton.UseUnderline = true;
			// Container child printViewButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w52 = new global::Gtk.HBox ();
			w52.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w53 = new global::Gtk.Image ();
			w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print-preview", global::Gtk.IconSize.Menu);
			w52.Add (w53);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w55 = new global::Gtk.Label ();
			w55.LabelProp = global::Mono.Unix.Catalog.GetString ("Druckvorschau");
			w55.UseUnderline = true;
			w52.Add (w55);
			w51.Add (w52);
			this.printViewButton.Add (w51);
			this.managementHbuttonbox.Add (this.printViewButton);
			global::Gtk.ButtonBox.ButtonBoxChild w59 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.managementHbuttonbox [this.printViewButton]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			// Container child managementHbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.exportButton = new global::Gtk.Button ();
			this.exportButton.CanFocus = true;
			this.exportButton.Name = "exportButton";
			this.exportButton.UseUnderline = true;
			// Container child exportButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_right", global::Gtk.IconSize.Menu);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w64.LabelProp = global::Mono.Unix.Catalog.GetString ("PDF - Export");
			w64.UseUnderline = true;
			w61.Add (w64);
			w60.Add (w61);
			this.exportButton.Add (w60);
			this.managementHbuttonbox.Add (this.exportButton);
			global::Gtk.ButtonBox.ButtonBoxChild w68 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.managementHbuttonbox [this.exportButton]));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			this.vbox4.Add (this.managementHbuttonbox);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.managementHbuttonbox]));
			w69.Position = 1;
			w69.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w70.Position = 2;
			w70.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w71.Position = 4;
			w71.Expand = false;
			w71.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.personalTreeView.CursorChanged += new global::System.EventHandler (this.OnPersonalTreeViewCursorChanged);
			this.PersonAddButton.Clicked += new global::System.EventHandler (this.OnPersonAddButtonClicked);
			this.PersonEditButton.Clicked += new global::System.EventHandler (this.OnPersonEditButtonClicked);
			this.printButton.Clicked += new global::System.EventHandler (this.OnPrintButtonClicked);
			this.printViewButton.Clicked += new global::System.EventHandler (this.OnPrintViewButtonClicked);
			this.exportButton.Clicked += new global::System.EventHandler (this.OnExportButtonClicked);
		}
	}
}
